global:
  scrape_interval: 15s
  scrape_timeout: 5s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['host.containers.internal:9100']
        labels:
          instance: 'macnode'
      - targets: ['atlas:9100']
        labels:
          instance: 'atlas'

  - job_name: 'gpu'
    static_configs:
      - targets: ['atlas:9835']
        labels:
          instance: 'atlas'
